Repository davidkurilla/refuel, pull requests merged in 2024-05, with the labels that each got.

#6 [FEATURE] Improve Error Handling for Expect Methods
  Cargo.lock
  src/main.rs
Labels: enhancement

#12 Update Cargo.toml to 0.1.2
  Cargo.lock
  Cargo.toml
Labels: build

#14 [BUG] Fix bug in TOML parser
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: bug

#18 [BUILD] Rename LICENSE to LICENSE-MIT and created LICENSE-APACHE and modify Cargo.toml manifest to account for license changes
  Cargo.toml
  LICENSE-APACHE
  LICENSE-MIT
Labels: build

#22 [DOCS] create contributing.md and code of conduct.md documents
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
Labels: documentation

#21 Update LICENSE-APACHE
  LICENSE-APACHE
Labels: build

#23 Add a unit test for InputData::postgres_url
  src/main.rs
  src/tests/mod.rs
Labels: testing
